# Generated by Django 4.2.4 on 2023-09-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_order_alter_customer_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
