# Generated by Django 4.2.4 on 2023-09-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rawmodel_alter_order_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
    ]
